### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by m11m** [Selene-Amanita/bevy_basic_portals#4]
Sorry if this is a known issue, but the crate doesn't seem to be working for me. The view through the portal is static no matter what angle I look at it.

![image](https://github.com/Selene-Amanita/bevy_basic_portals/assets/92771507/ab9a06e6-47e0-42f4-a22a-927b44ba4839)
![image](https://github.com/Selene-Amanita/bevy_basic_portals/assets/92771507/edce4fd2-812c-46de-9db5-11f99e3963f3)

### My machine
`AdapterInfo { name: "NVIDIA GeForce RTX 3080 Ti", vendor: 4318, device: 8712, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "535.113.01", backend: Vulkan }`

**Comment by Selene-Amanita** [comment]
@kayhhh Hi, thanks for your interest in that crate!
Did you resize the window after the portal creation?
If so it's a known issue, but I think I finally know how to fix it I just need to do it, I'll try if it works when migrating to Bevy 0.12.0 in a few days.
If not, is this the mirror example or did you modify it

**Comment by m11m** [comment]
I don't think I resized the window myself, but I use a tiling window manager that probably moved it around as it was created.
This is the mirror example, unmodified. I tried a few examples and using the library in my own code and all had the same issue.

**Comment by Selene-Amanita** [comment]
Solved by https://github.com/Selene-Amanita/bevy_basic_portals/commits/main
